#if defined _inc_admin_command_header
	#undef _inc_admin_command_header
#endif

#if defined _admin_command_header_included
	#endinput
#endif
#define _admin_command_header_included


#include	"admin_commands\acarinfo.pwn"

#include	"admin_commands\adminannouncement.pwn"

#include	"admin_commands\adminchat.pwn"

#include	"admin_commands\admins.pwn"

#include	"admin_commands\adminserverinfo.pwn"

#include	"admin_commands\alogin.pwn"

#include	"admin_commands\aprivatemessage.pwn"

#include	"admin_commands\aveh.pwn"

#include	"admin_commands\ban.pwn"

#include	"admin_commands\setcarcolour.pwn"

#include	"admin_commands\clearchat.pwn"

#include	"admin_commands\clearchatforplayer.pwn"

#include	"admin_commands\createactor.pwn"

#include	"admin_commands\createhouse.pwn"

#include	"admin_commands\createlabel.pwn"

#include	"admin_commands\createmapicon.pwn"

#include	"admin_commands\createpickup.pwn"

#include	"admin_commands\freezeplayer.pwn"

#include	"admin_commands\gethere.pwn"

#include	"admin_commands\getherecar.pwn"

#include	"admin_commands\getlocaladmin.pwn"

#include	"admin_commands\getmypos.pwn"

#include	"admin_commands\getplayerip.pwn"

#include	"admin_commands\giveplayerbankmoney.pwn"

#include	"admin_commands\giveplayercash.pwn"

#include	"admin_commands\giveplayergun.pwn"

#include	"admin_commands\giveplayerlicense.pwn"

#include	"admin_commands\giveplayerpayday.pwn"

#include	"admin_commands\goto.pwn"

#include	"admin_commands\gotocar.pwn"

#include	"admin_commands\jail.pwn"

#include	"admin_commands\jetpack.pwn"

#include	"admin_commands\kick.pwn"

#include	"admin_commands\levelupall.pwn"

#include	"admin_commands\levelupplayer.pwn"

#include	"admin_commands\makeleader.pwn"

#include	"admin_commands\mute.pwn"

#include	"admin_commands\payday.pwn"

#include	"admin_commands\repaircar.pwn"

#include	"admin_commands\setchatfloodertime.pwn"

#include	"admin_commands\setcommandfloodertime.pwn"

#include	"admin_commands\setplayeradmin.pwn"

#include	"admin_commands\setplayerarmour.pwn"

#include	"admin_commands\setplayerbankmoney.pwn"

#include	"admin_commands\setplayergender.pwn"

#include	"admin_commands\setplayergravity.pwn"

#include	"admin_commands\setplayerhealth.pwn"

#include	"admin_commands\setplayerinteriorid.pwn"

#include	"admin_commands\setplayerlevel.pwn"

#include	"admin_commands\setplayerlevelexp.pwn"

#include	"admin_commands\setplayermoney.pwn"

#include	"admin_commands\setplayerskin.pwn"

#include	"admin_commands\setplayertempskin.pwn"

#include	"admin_commands\setplayervirtualworld.pwn"

#include	"admin_commands\setplayerweaponskill.pwn"

#include	"admin_commands\settime.pwn"

#include	"admin_commands\setweaponmultiplier.pwn"

#include	"admin_commands\setweather.pwn"

#include	"admin_commands\slap.pwn"

#include	"admin_commands\spawnplayer.pwn"

#include	"admin_commands\takeplayerlicense.pwn"

#include	"admin_commands\tpcoor.pwn"
