#if defined _inc_player_command_header
	#undef _inc_player_command_header
#endif

#if defined _player_command_header_included
	#endinput
#endif
#define _player_command_header_included


#include	"player_commands\ame.pwn"

#include	"player_commands\coinflip.pwn"

#include	"player_commands\do.pwn"

#include	"player_commands\engine.pwn"

#include	"player_commands\gps.pwn"

#include	"player_commands\licenses.pwn"

#include	"player_commands\mainmenu.pwn"

#include	"player_commands\me.pwn"

#include	"player_commands\ooc.pwn"

#include	"player_commands\pay.pwn"

#include	"player_commands\privatemessage.pwn"

#include	"player_commands\shout.pwn"

#include	"player_commands\statistics.pwn"

#include	"player_commands\try.pwn"

#include	"player_commands\whisper.pwn"
